### ISSUE TITLE
Extending Vite config and using Vue.js framework issue

### ISSUE THREAD

**Issue by achwilko** [smapiot/piral-cli-vite#4]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

[Package Version, OS, Browser, ...]
piral: 1.3.3
piral-cli: 1.3.3
piral-cli-vite: 1.0.1
OS: Windows,
Browser: Chrome 119

## Description

Cannot use `piral-cli-vite` with Vue.js framework. Extending Vite config is also not working correctly.

## Steps to Reproduce

1. Clone MWE repo: https://gitlab.com/achwilko/mwe-piral-cli-vue
2. NPM install and build `shell` part
3. NPM install and run `mfe1` part
4. piral-cli-vite will show error "failed to load the config"

## Expected behavior

`piral-cli-vite` should work correctly using extended config via `vite.config.js` (including for example plugins like `@vitejs/plugin-vue`) and pilet should start locally and render Vue components using `piral-vue-3` converter.

## Actual behavior

`piral-cli-vite` is not working / bundling correctly while using extended config `vite.config.js` with `@vitejs/plugin-vue` to render Vue component (using `piral-vue-3` converter)

## Possible Origin / Solution

As discussed on Gitter (https://app.gitter.im/#/room/#piral-io_community:gitter.im), we could improve a little bit `piral-cli-vite` package for easier Vite configuration modification via `vite.config.js`

**Comment by FlorianRappl** [comment]
Fixed in 1.0.2.
