### ISSUE TITLE
Invalid URI regarding pilet styles while using Vue components

### ISSUE THREAD

**Issue by achwilko** [smapiot/piral-cli-vite#5]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

[Package Version, OS, Browser, ...]
piral: 1.3.3
piral-cli: 1.3.3
piral-cli-vite: 1.0.2
OS: Windows,
Browser: Chrome 119

## Description

[Description of the bug]
Vue components CSS styles cannot be loaded while using `piral-cli-vite` with `piral-vue-3`

## Steps to Reproduce

1. Clone MWE branch: https://gitlab.com/achwilko/mwe-piral-cli-vue/-/tree/fix/pilet-css-uri-issue?ref_type=heads
2. NPM install and build shell part
3. NPM install and run mfe1 part
4. piral-cli-vite will show the error "ERR Error: Invalid URI "/0/style.css?"

```
ERR Error: Invalid URI "/0/style.css?_=0.48254091596936854"
GET /$pilet-api/0/style.css?_=0.48254091596936854
```

## Expected behavior

CSS styles from Vue components (Page1.vue) should be applied and work correctly.

## Actual behavior

CSS styles from Vue component are not applied with error `ERR Error: Invalid URI "/0/style.css?`

## Possible Origin / Solution

As discussed on Gitter, maybe it's related to way how CSS styles are injected in vite pilets, eg.
https://github.com/smapiot/piral-cli-vite/blob/ebd3a37e9a002aa80dce6641da831183ec9763a3/packages/vite-plugin-pilet/src/banner.ts#L25

As a workaround for now (but not efficient regarding final build) is to override Vite config like below:
```
// vite.config.js

const pluginVue = require("@vitejs/plugin-vue");

module.exports = function (config) {
  config.plugins.push(pluginVue());

  // avoid using hashes to reference correctly to pilet CSS file
  config.build.rollupOptions.output.assetFileNames = "[name][extname]";

  return config;
};

```

Would be great to improve vite pilet CSS inject way to avoid the above issue.

**Comment by FlorianRappl** [comment]
Thanks - fixed in 1.0.3!
