### ISSUE TITLE
vite-tsconfig-paths alias imports do not work

### ISSUE THREAD

**Issue by grazinskis** [smapiot/piral-cli-vite#6]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

https://stackblitz.com/edit/vitejs-vite-rds4k3?file=src%2FApp.tsx
Browser environment, in this instance

```
    "piral-cli": "^1.4.2",
    "piral-cli-vite": "1.0.3",
    "piral-core": "^1.4.2",
    "vite": "^5.0.8",
    "vite-tsconfig-paths": "^4.2.2"
```

## Description

When running `piral debug`, the `vite-tsconfig-paths` plugin does not seem to be working. Aliased imports are failing.
It seems as if `vite.config.js` is not being loaded at all.

The alias `@src` is defined in `tsconfig.json` and loaded through `tsconfigPaths()` vite plugin.

## Steps to Reproduce

1. Open https://stackblitz.com/edit/vitejs-vite-rds4k3?file=src%2FApp.tsx
2. Standard vite dev build will run
3. In provided terminal, kill existing dev server and run `piral debug`

## Expected behavior

**Bold test** text should be visible at the top left of the layout

## Actual behavior

Project starts, but **Bold test** is missing and terminal is showing errors about a failing import

## Possible Origin / Solution

--

**Comment by FlorianRappl** [comment]
Have you read the README? Your vite config is wrong; it's not the format / filename that `piral-cli-vite` expects.

If I change this to a real *vite.config.js* with the correct export it works.

See: https://github.com/smapiot/piral-cli-vite/tree/develop/packages/piral-cli-vite#customizing
